### ISSUE TITLE
Text Simplification survey

### ISSUE THREAD

**Issue by nishkalavallabhi** [NiuTrans/ABigSurvey#1]
This list is cool!
I recently came across this survey of text simplification - https://www.mitpressjournals.org/doi/full/10.1162/COLI_a_00370
can you perhaps add to your list? There were a couple more I read recently - e.g., on question generation. Should I add them and send a PR or is it better to raise as issues?

**Comment by libeineu** [comment]
Thanks! We appreciate that you can add them to our survey list! Just send a PR and we will merge it soon!
