### ISSUE TITLE
Can you add our Neural IR survey to the list?

### ISSUE THREAD

**Issue by rodrigonogueira4** [NiuTrans/ABigSurvey#12]
[Pretrained Transformers for Text Ranking: BERT and Beyond](https://arxiv.org/abs/2010.06467)

**Comment by xiaotong** [comment]
thanks for the suggestion. Yes, it is fine with adding it into the list.

**Comment by rodrigonogueira4** [comment]
but should I create a PR or you will do it?

**Comment by Zhoushuhan1013** [comment]
> but should I create a PR or you will do it?

Thank you for your suggestion. We will add your Neural IR survey to the list in the next update.

**Comment by Zhoushuhan1013** [comment]
> but should I create a PR or you will do it?

Thank you for your suggestion. We will add your Neural IR survey to the list in the next update.

**Comment by rodrigonogueira4** [comment]
Great, thanks!
