### ISSUE TITLE
Add journal paper link

### ISSUE THREAD

**Issue by ghost** [NiuTrans/ABigSurvey#3]
For the survey paper "**SECNLP: A survey of embeddings in clinical natural language processing**", can you please include the journal paper (**updated version**) link "https://www.sciencedirect.com/science/article/pii/S1532046419302436" instead of arxiv link?

**Comment by libeineu** [comment]
Sorry about that! We will update the link. Thanks for your advice!

**Comment by libeineu** [comment]
We have already updated the link!
